// Generated from the live boohooMAN Premium Essentials collection (Algolia feed, 08 Sep 2026).
// Source: https://www.boohooman.com/categories/mens-premium-essentials — images mirrored to img/products (600px).
window.PE_FAMILIES=[{"id": "zip-hoodie", "label": "Zip Hoodies", "count": 6}, {"id": "oth-hoodie", "label": "Hoodies", "count": 4}, {"id": "quarter-zip", "label": "1/4 Zips", "count": 5}, {"id": "sweatshirt", "label": "Sweatshirts", "count": 5}, {"id": "ls-tee", "label": "Long Sleeve Tees", "count": 5}, {"id": "tee", "label": "T-Shirts", "count": 6}, {"id": "straight-jogger", "label": "Straight Leg Joggers", "count": 3}, {"id": "wide-jogger", "label": "Wide Leg Joggers", "count": 6}];
window.PE_PRODUCTS=[
{
"id": "CMM29606",
"fam": "oth-hoodie",
"name": "Regular Fit Premium 480gsm Washed Over the Head Hoodie",
"colour": "Washed Chocolate",
"price": 30,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L"
],
"img": "img/products/cmm29606.jpg",
"img2": "img/products/cmm29606_2.jpg",
"sw": "img/products/cmm29606_s.jpg",
"slug": "boohooman-regular-fit-premium-480gsm-washed-over-the-head-hoodie_cmm29606",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback construction delivers a satisfyingly thick, substantial feel that holds its shape wash after wash</li>\n        <li>Regular fit cut through the shoulders and body for a relaxed, easy-wearing silhouette that works across a range of builds</li>\n        <l",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29621",
"fam": "tee",
"name": "Oversized Premium 280gsm Washed T-Shirt",
"colour": "Washed Chocolate",
"price": 16,
"was": null,
"sizes": [
"S",
"M"
],
"img": "img/products/cmm29621.jpg",
"img2": "img/products/cmm29621_2.jpg",
"sw": "img/products/cmm29621_s.jpg",
"slug": "boohooman-oversized-premium-280gsm-washed-t-shirt_cmm29621",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight single jersey cotton construction delivers a substantial, quality feel with a lived-in, washed finish that adds instant character</li>\n        <li>Oversized fit offers a relaxed, dropped shoulder silhouette for that effortlessly cool, laid-back aesthetic</li>\n ",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29612",
"fam": "sweatshirt",
"name": "Oversized Premium 480gsm Washed Sweatshirt",
"colour": "Washed Chocolate",
"price": 28,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL"
],
"img": "img/products/cmm29612.jpg",
"img2": "img/products/cmm29612_2.jpg",
"sw": "img/products/cmm29612_s.jpg",
"slug": "boohooman-oversized-premium-480gsm-washed-sweatshirt_cmm29612",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback construction delivers a substantial, structured feel that holds its shape wear after wear</li>\n        <li>Washed finish gives the sweatshirt an effortlessly worn-in, lived-in aesthetic straight out of the bag</li>\n        <li>Oversized regular fit thr",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29598",
"fam": "zip-hoodie",
"name": "Oversized Boxy Premium 480gsm Washed Zip Through Hoodie",
"colour": "Washed Navy",
"price": 35,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL",
"2XL"
],
"img": "img/products/cmm29598.jpg",
"img2": "img/products/cmm29598_2.jpg",
"sw": "img/products/cmm29598_s.jpg",
"slug": "boohooman-oversized-boxy-premium-480gsm-washed-zip-through-hoodie_cmm29598",
"gallery": [
"img/products/cmm29598_g0.jpg",
"img/products/cmm29598_g1.jpg",
"img/products/cmm29598_g2.jpg",
"img/products/cmm29598_g3.jpg"
],
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback fabric construction delivers a substantial, structured feel with a satisfyingly thick weight that holds its shape wear after wear</li>\n        <li>Oversized boxy fit sits wide across the shoulders and chest, dropping into a relaxed, square silhouette t",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29652",
"fam": "straight-jogger",
"name": "Straight Leg Premium 480gsm Washed Jogger",
"colour": "Washed Navy",
"price": 30,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL",
"2XL",
"3XL",
"4XL",
"5XL"
],
"img": "img/products/cmm29652.jpg",
"img2": "img/products/cmm29652_2.jpg",
"sw": "img/products/cmm29652_s.jpg",
"slug": "boohooman-straight-leg-premium-480gsm-washed-jogger_cmm29652",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback fabric construction delivers a substantial, structured feel that holds its shape wear after wear</li>\n        <li>Straight leg cut offers a clean, modern silhouette that sits comfortably through the thigh and falls evenly to the ankle</li>\n        <li>",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29620",
"fam": "tee",
"name": "Oversized Premium 280gsm Washed T-Shirt",
"colour": "Washed Navy",
"price": 16,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL",
"2XL",
"3XL",
"5XL"
],
"img": "img/products/cmm29620.jpg",
"img2": "img/products/cmm29620_2.jpg",
"sw": "img/products/cmm29620_s.jpg",
"slug": "boohooman-oversized-premium-280gsm-washed-t-shirt_cmm29620",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight single jersey cotton construction delivers a substantial, quality feel with a satisfying weight that holds its shape wear after wear</li>\n        <li>Oversized fit offers a relaxed, roomy silhouette through the shoulders and body for that effortlessly laid-back",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29645",
"fam": "quarter-zip",
"name": "Regular Fit Premium 480gsm 1/4 Zip Funnel Neck Washed Sweatshirt",
"colour": "Washed Navy",
"price": 30,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL",
"2XL",
"3XL",
"4XL",
"5XL"
],
"img": "img/products/cmm29645.jpg",
"img2": "img/products/cmm29645_2.jpg",
"sw": "img/products/cmm29645_s.jpg",
"slug": "boohooman-regular-fit-premium-480gsm-1-4-zip-funnel-neck-washed-sweatshirt_cmm29645",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback fabric construction delivers a substantial, structured feel that holds its shape wear after wear</li>\n        <li>Quarter-zip funnel neck design adds a distinctive utilitarian edge, offering adjustable coverage and a standout silhouette</li>\n        <l",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29592",
"fam": "zip-hoodie",
"name": "Oversized Boxy Premium 480gsm Zip Through Hoodie",
"colour": "Stone",
"price": 35,
"was": null,
"sizes": [
"S",
"M",
"L",
"XL"
],
"img": "img/products/cmm29592.jpg",
"img2": "img/products/cmm29592_2.jpg",
"sw": "img/products/cmm29592_s.jpg",
"slug": "boohooman-oversized-boxy-premium-480gsm-zip-through-hoodie_cmm29592",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback fabric construction delivers a substantial, structured feel with a satisfying weight that holds its shape wear after wear</li>\n        <li>Oversized boxy fit sits wide across the shoulders and chest, dropping into a relaxed, square silhouette that defi",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29656",
"fam": "wide-jogger",
"name": "Wide Leg Premium 480gsm Jogger",
"colour": "Stone",
"price": 30,
"was": null,
"sizes": [
"S",
"M",
"L"
],
"img": "img/products/cmm29656.jpg",
"img2": "img/products/cmm29656_2.jpg",
"sw": "img/products/cmm29656_s.jpg",
"slug": "boohooman-wide-leg-premium-480gsm-jogger_cmm29656",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Wide leg silhouette offering a relaxed, contemporary fit that sits comfortably through the seat and thigh</li>\n        <li>Crafted from loopback fabric for a satisfyingly weighty feel with a smooth outer finish and soft interior</li>\n        <li>Heavyweight construction th",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29622",
"fam": "tee",
"name": "Oversized Premium 280gsm T-Shirt",
"colour": "Stone",
"price": 16,
"was": null,
"sizes": [
"S",
"M",
"L",
"XL"
],
"img": "img/products/cmm29622.jpg",
"img2": "img/products/cmm29622_2.jpg",
"sw": "img/products/cmm29622_s.jpg",
"slug": "boohooman-oversized-premium-280gsm-t-shirt_cmm29622",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight single jersey cotton construction delivers a substantial, quality feel with a structured drape that holds its shape wear after wear</li>\n        <li>Oversized fit offers a relaxed, roomy silhouette through the shoulders and body for that effortlessly laid-back ",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29639",
"fam": "quarter-zip",
"name": "Regular Fit Premium 480gsm 1/4 Zip Funnel Neck Sweatshirt",
"colour": "Stone",
"price": 30,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL"
],
"img": "img/products/cmm29639.jpg",
"img2": "img/products/cmm29639_2.jpg",
"sw": "img/products/cmm29639_s.jpg",
"slug": "boohooman-regular-fit-premium-480gsm-1-4-zip-funnel-neck-sweatshirt_cmm29639",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback fabric construction delivers a substantial, structured feel with a satisfying weight that holds its shape wear after wear</li>\n        <li>Quarter-zip funnel neck design adds a refined edge to casual dressing, offering adjustable coverage and a distinc",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29596",
"fam": "zip-hoodie",
"name": "Oversized Boxy Premium 480gsm Zip Through Hoodie",
"colour": "Light Blue",
"price": 35,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L"
],
"img": "img/products/cmm29596.jpg",
"img2": "img/products/cmm29596_2.jpg",
"sw": "img/products/cmm29596_s.jpg",
"slug": "boohooman-oversized-boxy-premium-480gsm-zip-through-hoodie_cmm29596",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback fabric construction delivers a substantial, structured feel with a satisfying weight that holds its shape wear after wear</li>\n        <li>Oversized boxy fit sits wide across the shoulders and chest, creating that sought-after dropped-shoulder silhouet",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29647",
"fam": "straight-jogger",
"name": "Straight Leg Premium 480gsm Jogger",
"colour": "Light Blue",
"price": 30,
"was": null,
"sizes": [
"S",
"M",
"L"
],
"img": "img/products/cmm29647.jpg",
"img2": "img/products/cmm29647_2.jpg",
"sw": "img/products/cmm29647_s.jpg",
"slug": "boohooman-straight-leg-premium-480gsm-jogger_cmm29647",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback fabric construction delivers a satisfyingly dense, structured feel that holds its shape wear after wear</li>\n        <li>Straight leg cut offers a clean, unfussy silhouette that sits comfortably through the thigh and falls evenly to the ankle</li>\n    ",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29640",
"fam": "quarter-zip",
"name": "Regular Fit Premium 480gsm 1/4 Zip Funnel Neck Sweatshirt",
"colour": "Light Blue",
"price": 30,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL"
],
"img": "img/products/cmm29640.jpg",
"img2": "img/products/cmm29640_2.jpg",
"sw": "img/products/cmm29640_s.jpg",
"slug": "boohooman-regular-fit-premium-480gsm-1-4-zip-funnel-neck-sweatshirt_cmm29640",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback fabric construction delivers a substantial, structured feel with a satisfying weight that holds its shape wear after wear</li>\n        <li>Quarter-zip funnel neck design adds a sharp, utilitarian edge - zip up fully for a sleek, streamlined silhouette ",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29625",
"fam": "tee",
"name": "Oversized Premium 280gsm T-Shirt",
"colour": "Light Blue",
"price": 16,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL"
],
"img": "img/products/cmm29625.jpg",
"img2": "img/products/cmm29625_2.jpg",
"sw": "img/products/cmm29625_s.jpg",
"slug": "boohooman-oversized-premium-280gsm-t-shirt_cmm29625",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight single jersey cotton construction delivers a substantial, structured feel that holds its shape wear after wear</li>\n        <li>Oversized fit offers a relaxed, roomy silhouette with dropped shoulders and an extended body length for that effortless street-ready ",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29597",
"fam": "zip-hoodie",
"name": "Oversized Boxy Premium 480gsm Washed Zip Through Hoodie",
"colour": "Washed Chocolate",
"price": 35,
"was": null,
"sizes": [
"M"
],
"img": "img/products/cmm29597.jpg",
"img2": "img/products/cmm29597_2.jpg",
"sw": "img/products/cmm29597_s.jpg",
"slug": "boohooman-oversized-boxy-premium-480gsm-washed-zip-through-hoodie_cmm29597",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback fabric construction delivers a substantial, structured feel with a lived-in washed finish that adds instant character</li>\n        <li>Oversized boxy fit sits wide across the shoulders and chest, creating a relaxed, dropped silhouette that's built for ",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29654",
"fam": "wide-jogger",
"name": "Wide Leg Premium 480gsm Washed Jogger",
"colour": "Washed Chocolate",
"price": 30,
"was": null,
"sizes": [
"XS",
"S",
"M"
],
"img": "img/products/cmm29654.jpg",
"img2": "img/products/cmm29654_2.jpg",
"sw": "img/products/cmm29654_s.jpg",
"slug": "boohooman-wide-leg-premium-480gsm-washed-jogger_cmm29654",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Wide leg silhouette crafted in a loopback fabric for a relaxed, street-ready drape</li>\n        <li>Heavyweight construction offering substantial weight and structure for a premium-feel finish</li>\n        <li>Washed finish lending an effortlessly worn-in aesthetic straigh",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29641",
"fam": "quarter-zip",
"name": "Regular Fit Premium 480gsm 1/4 Zip Funnel Neck Washed Sweatshirt",
"colour": "Washed Chocolate",
"price": 30,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL"
],
"img": "img/products/cmm29641.jpg",
"img2": "img/products/cmm29641_2.jpg",
"sw": "img/products/cmm29641_s.jpg",
"slug": "boohooman-regular-fit-premium-480gsm-1-4-zip-funnel-neck-washed-sweatshirt_cmm29641",
"gallery": null,
"desc": "Heavyweight 480GSM Regular Fit 1/4 Zip Washed Funnel Neck Sweater",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29630",
"fam": "ls-tee",
"name": "Regular Fit Premium 280gm Washed Long Sleeve T-Shirt",
"colour": "Washed Chocolate",
"price": 20,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL",
"2XL",
"3XL",
"4XL",
"5XL"
],
"img": "img/products/cmm29630.jpg",
"img2": "img/products/cmm29630_2.jpg",
"sw": "img/products/cmm29630_s.jpg",
"slug": "boohooman-regular-fit-premium-280gm-washed-long-sleeve-t-shirt_cmm29630",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight single jersey cotton construction delivers a satisfying weight and structure that holds its shape wear after wear</li>\n        <li>Washed finish gives the fabric a lived-in, broken-in character straight out of the bag - no waiting required</li>\n        <li>Clas",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29603",
"fam": "oth-hoodie",
"name": "Regular Fit Premium 480gsm Over the Head Hoodie",
"colour": "Stone",
"price": 30,
"was": null,
"sizes": [
"XS",
"M",
"L",
"XL"
],
"img": "img/products/cmm29603.jpg",
"img2": "img/products/cmm29603_2.jpg",
"sw": "img/products/cmm29603_s.jpg",
"slug": "boohooman-regular-fit-premium-480gsm-over-the-head-hoodie_cmm29603",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback fabric construction delivers a substantial, structured feel that holds its shape wear after wear</li>\n        <li>Classic over-the-head silhouette with a generous hood for an effortlessly laid-back finish</li>\n        <li>Regular fit cut through the sh",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29648",
"fam": "straight-jogger",
"name": "Straight Leg Premium 480gsm Jogger",
"colour": "Stone",
"price": 30,
"was": null,
"sizes": [
"S",
"M"
],
"img": "img/products/cmm29648.jpg",
"img2": "img/products/cmm29648_2.jpg",
"sw": "img/products/cmm29648_s.jpg",
"slug": "boohooman-straight-leg-premium-480gsm-jogger_cmm29648",
"gallery": null,
"desc": "<div>    <ul>        <li>Heavyweight loopback fabric construction delivers a satisfying weight and durability that holds its shape wear after wear</li>        <li>Straight leg cut offers a clean, modern silhouette that sits comfortably through the thigh and falls evenly to the ankle</li>        <li>",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29616",
"fam": "sweatshirt",
"name": "Oversized Premium 480gsm Sweatshirt",
"colour": "Stone",
"price": 28,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL"
],
"img": "img/products/cmm29616.jpg",
"img2": "img/products/cmm29616_2.jpg",
"sw": "img/products/cmm29616_s.jpg",
"slug": "boohooman-oversized-premium-480gsm-sweatshirt_cmm29616",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback construction delivers a substantial, structured feel that holds its shape wear after wear</li>\n        <li>Oversized regular fit through the shoulders and body for that effortlessly relaxed, street-ready silhouette</li>\n        <li>Classic crew necklin",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29631",
"fam": "ls-tee",
"name": "Regular Fit Premium 280GSM Long Sleeve T-Shirt",
"colour": "Stone",
"price": 20,
"was": null,
"sizes": [
"S",
"M",
"L",
"XL"
],
"img": "img/products/cmm29631.jpg",
"img2": "img/products/cmm29631_2.jpg",
"sw": "img/products/cmm29631_s.jpg",
"slug": "boohooman-regular-fit-premium-280gsm-long-sleeve-t-shirt_cmm29631",
"gallery": null,
"desc": "<div>    <ul>        <li>Heavyweight single jersey cotton construction delivers a satisfying weight and structure that holds its shape wear after wear</li>        <li>Regular fit cut offers a relaxed, easy silhouette through the chest and shoulders without feeling oversized</li>        <li>Classic c",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29605",
"fam": "oth-hoodie",
"name": "Regular Fit Premium 480gsm Washed Over the Head Hoodie",
"colour": "Washed Navy",
"price": 30,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL",
"2XL",
"3XL",
"4XL",
"5XL"
],
"img": "img/products/cmm29605.jpg",
"img2": "img/products/cmm29605_2.jpg",
"sw": "img/products/cmm29605_s.jpg",
"slug": "boohooman-regular-fit-premium-480gsm-washed-over-the-head-hoodie_cmm29605",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback construction delivers a substantial, structured feel that holds its shape wear after wear</li>\n        <li>Washed finish gives the hoodie a lived-in, broken-in aesthetic straight out of the bag</li>\n        <li>Over-the-head design with a classic hood ",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29657",
"fam": "wide-jogger",
"name": "Wide Leg Premium 480gsm Washed Jogger",
"colour": "Washed Navy",
"price": 30,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL",
"3XL"
],
"img": "img/products/cmm29657.jpg",
"img2": "img/products/cmm29657_2.jpg",
"sw": "img/products/cmm29657_s.jpg",
"slug": "boohooman-wide-leg-premium-480gsm-washed-jogger_cmm29657",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Wide leg silhouette crafted in a heavyweight loopback fabric for a substantial, structured drape</li>\n        <li>Washed finish gives these joggers a lived-in, worn-in aesthetic that sets them apart from standard sweats</li>\n        <li>Relaxed through the seat and thigh w",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29618",
"fam": "sweatshirt",
"name": "Oversized Premium 480gsm Washed Sweatshirt",
"colour": "Washed Navy",
"price": 28,
"was": null,
"sizes": [
"XS",
"M",
"L",
"XL",
"2XL",
"3XL"
],
"img": "img/products/cmm29618.jpg",
"img2": "img/products/cmm29618_2.jpg",
"sw": "img/products/cmm29618_s.jpg",
"slug": "boohooman-oversized-premium-480gsm-washed-sweatshirt_cmm29618",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback construction delivers a satisfying weight and structure that holds its shape wear after wear</li>\n        <li>Washed finish gives the sweatshirt an effortlessly worn-in, lived-in character straight out of the bag</li>\n        <li>Oversized regular fit ",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29629",
"fam": "ls-tee",
"name": "Regular Fit Premium 280gm Washed Long Sleeve T-Shirt",
"colour": "Washed Navy",
"price": 20,
"was": null,
"sizes": [
"XS",
"S",
"M",
"XL"
],
"img": "img/products/cmm29629.jpg",
"img2": "img/products/cmm29629_2.jpg",
"sw": "img/products/cmm29629_s.jpg",
"slug": "boohooman-regular-fit-premium-280gm-washed-long-sleeve-t-shirt_cmm29629",
"gallery": null,
"desc": "Heavyweight Regular Fit Washed Long Sleeve T-Shirt",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29595",
"fam": "zip-hoodie",
"name": "Oversized Boxy Premium 480gsm Washed Zip Through Hoodie",
"colour": "Washed Charcoal",
"price": 35,
"was": null,
"sizes": [
"S",
"M",
"L",
"3XL"
],
"img": "img/products/cmm29595.jpg",
"img2": "img/products/cmm29595_2.jpg",
"sw": "img/products/cmm29595_s.jpg",
"slug": "boohooman-oversized-boxy-premium-480gsm-washed-zip-through-hoodie_cmm29595",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback fabric construction delivers a substantial, quality feel with a satisfyingly thick weight that holds its shape wear after wear</li>\n        <li>Oversized boxy fit offers a relaxed, roomy silhouette through the shoulders and body for that effortlessly l",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29658",
"fam": "wide-jogger",
"name": "Wide Leg Premium 480gsm Washed Jogger",
"colour": "Washed Charcoal",
"price": 30,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL",
"2XL",
"3XL",
"4XL",
"5XL"
],
"img": "img/products/cmm29658.jpg",
"img2": "img/products/cmm29658_2.jpg",
"sw": "img/products/cmm29658_s.jpg",
"slug": "boohooman-wide-leg-premium-480gsm-washed-jogger_cmm29658",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Wide leg silhouette crafted in a substantial loopback fabric for a relaxed, oversized drape through the leg</li>\n        <li>Washed finish gives these joggers a lived-in, worn-in aesthetic that adds instant character and depth to the look</li>\n        <li>Heavyweight const",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29634",
"fam": "ls-tee",
"name": "Regular Fit Premium 280gm Washed Long Sleeve T-Shirt",
"colour": "Washed Charcoal",
"price": 20,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL",
"3XL",
"4XL"
],
"img": "img/products/cmm29634.jpg",
"img2": "img/products/cmm29634_2.jpg",
"sw": "img/products/cmm29634_s.jpg",
"slug": "boohooman-regular-fit-premium-280gm-washed-long-sleeve-t-shirt_cmm29634",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight single jersey cotton construction delivers a satisfying weight and structure that holds its shape wear after wear</li>\n        <li>Washed finish gives the fabric a lived-in, broken-in character straight out of the bag</li>\n        <li>Classic crew neckline keep",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29623",
"fam": "tee",
"name": "Oversized Premium 280gsm Washed T-Shirt",
"colour": "Washed Charcoal",
"price": 16,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L"
],
"img": "img/products/cmm29623.jpg",
"img2": "img/products/cmm29623_2.jpg",
"sw": "img/products/cmm29623_s.jpg",
"slug": "boohooman-oversized-premium-280gsm-washed-t-shirt_cmm29623",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight single jersey cotton construction delivers a substantial, structured feel that holds its shape wear after wear</li>\n        <li>Oversized fit drops through the shoulders and chest for that relaxed, roomy silhouette that's central to contemporary streetwear</li>",
"care": "100% Cotton. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29602",
"fam": "oth-hoodie",
"name": "Regular Fit Premium 480gsm Over the Head Hoodie",
"colour": "Light Blue",
"price": 30,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL"
],
"img": "img/products/cmm29602.jpg",
"img2": "img/products/cmm29602_2.jpg",
"sw": "img/products/cmm29602_s.jpg",
"slug": "boohooman-regular-fit-premium-480gsm-over-the-head-hoodie_cmm29602",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback fabric construction delivers a substantial, structured feel that holds its shape wear after wear</li>\n        <li>Classic over-the-head silhouette with a generous hood for an effortlessly laid-back finish</li>\n        <li>Regular fit cut through the sh",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29659",
"fam": "wide-jogger",
"name": "Wide Leg Premium 480gsm Jogger",
"colour": "Light Blue",
"price": 30,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL"
],
"img": "img/products/cmm29659.jpg",
"img2": "img/products/cmm29659_2.jpg",
"sw": "img/products/cmm29659_s.jpg",
"slug": "boohooman-wide-leg-premium-480gsm-jogger_cmm29659",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Wide leg silhouette cut for a relaxed, street-ready fit that sits comfortably through the seat and thigh</li>\n        <li>Crafted from a loopback fabric construction for a substantial, structured feel with a soft interior finish</li>\n        <li>Heavyweight build that hold",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29632",
"fam": "ls-tee",
"name": "Regular Fit Premium 280gsm Long Sleeve T-Shirt",
"colour": "Light Blue",
"price": 20,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL"
],
"img": "img/products/cmm29632.jpg",
"img2": "img/products/cmm29632_2.jpg",
"sw": "img/products/cmm29632_s.jpg",
"slug": "boohooman-regular-fit-premium-280gsm-long-sleeve-t-shirt_cmm29632",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight single jersey cotton construction delivers a satisfying weight and structure that holds its shape wear after wear</li>\n        <li>Regular fit cut offers a relaxed, easy silhouette through the chest and shoulders without feeling oversized</li>\n        <li>Class",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29615",
"fam": "sweatshirt",
"name": "Oversized Premium 480gsm Sweatshirt",
"colour": "Light Blue",
"price": 28,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL"
],
"img": "img/products/cmm29615.jpg",
"img2": "img/products/cmm29615_2.jpg",
"sw": "img/products/cmm29615_s.jpg",
"slug": "boohooman-oversized-premium-480gsm-sweatshirt_cmm29615",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback construction delivers a substantial, structured feel with a satisfyingly thick weight that holds its shape wear after wear</li>\n        <li>Oversized regular fit through the shoulders and body creates that effortlessly relaxed silhouette that's central",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29591",
"fam": "zip-hoodie",
"name": "Oversized Boxy Premium 480gsm Zip Through Hoodie",
"colour": "Black",
"price": 35,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL",
"2XL",
"3XL"
],
"img": "img/products/cmm29591.jpg",
"img2": "img/products/cmm29591_2.jpg",
"sw": "img/products/cmm29591_s.jpg",
"slug": "boohooman-oversized-boxy-premium-480gsm-zip-through-hoodie_cmm29591",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback fabric construction delivers a substantial, structured feel with a satisfying weight that holds its shape wear after wear</li>\n        <li>Oversized boxy fit sits wide across the shoulders and chest, creating that sought-after relaxed silhouette that d",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29660",
"fam": "wide-jogger",
"name": "Wide Leg Premium 480gsm Jogger",
"colour": "Black",
"price": 30,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL",
"3XL"
],
"img": "img/products/cmm29660.jpg",
"img2": "img/products/cmm29660_2.jpg",
"sw": "img/products/cmm29660_s.jpg",
"slug": "boohooman-wide-leg-premium-480gsm-jogger_cmm29660",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Wide leg silhouette cut for a relaxed, oversized drape that sits comfortably through the hip and thigh</li>\n        <li>Loopback fabric construction delivers a satisfying weight and softness, built to hold its shape wear after wear</li>\n        <li>Heavyweight build makes ",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29619",
"fam": "sweatshirt",
"name": "Oversized Premium 480gsm Sweatshirt",
"colour": "Black",
"price": 28,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"2XL",
"3XL"
],
"img": "img/products/cmm29619.jpg",
"img2": "img/products/cmm29619_2.jpg",
"sw": "img/products/cmm29619_s.jpg",
"slug": "boohooman-oversized-premium-480gsm-sweatshirt_cmm29619",
"gallery": null,
"desc": "<div>\n    <ul>\n        <li>Heavyweight loopback construction delivers a substantial, structured feel that holds its shape wear after wear</li>\n        <li>Oversized regular fit through the shoulders and body for that effortlessly relaxed, dropped silhouette</li>\n        <li>Classic crew neckline kee",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29628",
"fam": "tee",
"name": "Oversized Premium 280gsm T-Shirt",
"colour": "Black",
"price": 16,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"2XL",
"4XL",
"5XL"
],
"img": "img/products/cmm29628.jpg",
"img2": "img/products/cmm29628_2.jpg",
"sw": "img/products/cmm29628_s.jpg",
"slug": "boohooman-oversized-premium-280gsm-t-shirt_cmm29628",
"gallery": null,
"desc": "<div>    <ul>        <li>Heavyweight single jersey cotton construction delivers a substantial, structured feel that holds its shape wear after wear</li>        <li>Oversized fit offers a relaxed, roomy silhouette with dropped shoulders and an extended body length for that effortless street-ready loo",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
},
{
"id": "CMM29643",
"fam": "quarter-zip",
"name": "Regular Fit Premium 480gsm 1/4 Zip Funnel Neck Sweatshirt",
"colour": "Black",
"price": 30,
"was": null,
"sizes": [
"XS",
"S",
"M",
"L",
"XL",
"2XL",
"3XL"
],
"img": "img/products/cmm29643.jpg",
"img2": "img/products/cmm29643_2.jpg",
"sw": "img/products/cmm29643_s.jpg",
"slug": "boohooman-regular-fit-premium-480gsm-1-4-zip-funnel-neck-sweatshirt_cmm29643",
"gallery": null,
"desc": "<div>    <ul>        <li>Heavyweight loopback fabric construction delivers a substantial, structured feel that holds its shape wear after wear</li>        <li>Quarter-zip funnel neck design adds a distinctive sportswear-inspired edge, offering adjustable coverage and a sharp finish at the collar</li",
"care": "80% Cotton, 20% Polyester. Model is 6'1 & wears UK size M/32"
}
];
